kit:
  name: "Qubell Selenium Grid"
  link: https://github.com/qubell-bazaar/component-selenium-grid
  applications: 
    - name: "Selenium Grid"
      manifest: https://raw.github.com/qubell-bazaar/component-selenium-grid/master/component-selenium-grid.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
